version: '3.8'

services:
  bot:
    build: .
    container_name: telegram_bot
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
