[phases]

[phases.setup]
packages = ["glibc", "nodejs", "python3"]

[variables]
NODE_VERSION = "18"
PYTHON_VERSION = "3.11"

[build]
nixpkgs_inputs = [
    "glibc",
    "glibcLocales",
    "gcc",
]

[variables]
GLIBC_VERSION = "2.38"

[customizations.build]
build_cmd = """
    # Установка GLIBC и других зависимостей, необходимых для вашей среды
    apt-get update
    apt-get install -y gcc libc6-dev make wget
    wget http://ftp.gnu.org/gnu/libc/glibc-2.38.tar.gz
    tar -xvf glibc-2.38.tar.gz
    cd glibc-2.38 && mkdir build && cd build
    ../configure --prefix=/usr && make && make install
  """
